### ISSUE TITLE
Huggingface 404 Client Error

### ISSUE THREAD

**Issue by Gallrax** [kpthedev/ez-text2video#4]
Fill in "dog" for the default open page content, then click "generate", and an error is reported as follows

`Traceback (most recent call last):
  File "/Users/gallrax/anaconda3/envs/t2v/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/Users/gallrax/mine/ez-text2video/app.py", line 124, in <module>
    main()
  File "/Users/gallrax/mine/ez-text2video/app.py", line 102, in main
    raw_video = generate(
  File "/Users/gallrax/mine/ez-text2video/lib/generate.py", line 63, in generate
    pipeline = make_pipeline_generator(
  File "/Users/gallrax/anaconda3/envs/t2v/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 194, in wrapper
    return cached_func(*args, **kwargs)
  File "/Users/gallrax/anaconda3/envs/t2v/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 223, in __call__
    return self._get_or_create_cached_value(args, kwargs)
  File "/Users/gallrax/anaconda3/envs/t2v/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 248, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
  File "/Users/gallrax/anaconda3/envs/t2v/lib/python3.10/site-packages/streamlit/runtime/caching/cache_utils.py", line 302, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
  File "/Users/gallrax/mine/ez-text2video/lib/generate.py", line 36, in make_pipeline_generator
    pipeline = DiffusionPipeline.from_pretrained(
  File "/Users/gallrax/anaconda3/envs/t2v/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 884, in from_pretrained
    cached_folder = cls.download(
  File "/Users/gallrax/anaconda3/envs/t2v/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1218, in download
    info = model_info(
  File "/Users/gallrax/anaconda3/envs/t2v/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/gallrax/anaconda3/envs/t2v/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1604, in model_info
    hf_raise_for_status(r)
  File "/Users/gallrax/anaconda3/envs/t2v/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 301, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/damo-vilab/text-to-video-ms-1.7b (Request ID: Root=1-645a45fb-0fe6d3d6342f4dcd39e89529)`

**Comment by kpthedev** [comment]
It seems like you have a connection error to the Hugging Face API for downloading the models. The API isn't down or anything, so maybe try checking your internet connection.
